
[functions.transcribe-video]
enabled = true
verify_jwt = true
import_map = "./functions/transcribe-video/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/transcribe-video/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/transcribe-video/*.html" ]

[functions.notify-new-lead]
enabled = true
verify_jwt = true
import_map = "./functions/notify-new-lead/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-new-lead/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-new-lead/*.html" ]
